# Projects paths
pipeline_root: "/opt/literature-sem-search"
pipeline_code_dir: "{{ pipeline_root }}/code"
pipeline_data_dir: "{{ pipeline_root }}/data"
pipeline_tools_dir: "{{ pipeline_root }}/tools"
pipeline_venv_dir: "{{ pipeline_root }}/venv"

# Addresses
controller_ip: "{{ hostvars[groups['controller'][0]].ansible_host }}"

# Dask config
dask_scheduler_port: 8786
dask_dashboard_port: 8787
dask_scheduler_url: "tcp://{{ controller_ip }}:{{ dask_scheduler_port }}"
dask_dashboard_address: "{{ controller_ip }}:{{ dask_dashboard_port }}"

# Prefect config
prefect_server_port: 4200
prefect_api_url: "http://{{ controller_ip }}:{{ prefect_server_port }}/api"
prefect_ui_url: "http://{{ controller_ip }}:{{ prefect_server_port }}"