- name: Install minio_server Python dependencies
  ansible.builtin.pip:
    virtualenv: "{{ pipeline_venv_dir }}"
    name: "{{ minio_python_deps }}"
    state: latest

- name: Download MinIO binary
  become: true
  ansible.builtin.get_url:
    url: "{{ minio_install_url }}"
    dest: "{{ minio_path }}"
    mode: '0755'

- name: Create MinIO data directory
  become: true
  ansible.builtin.file:
    path: "{{ minio_data_dir }}"
    state: directory
    mode: '0755'
    owner: almalinux
    group: almalinux