minio_python_deps:
  - minio

minio_install_url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
minio_path: "/usr/local/bin/minio"
minio_data_dir: "{{ pipeline_data_dir }}/minio"
minio_root_user: "minioadmin"
minio_root_password: "minioadmin"
minio_bucket_name: "lit-sem-search-bucket"
minio_console_port: 9001