- hosts: all
  roles:
    - common
    - pipeline_code

- hosts: controller
  roles:
    - dask_scheduler
    - minio_server
    - prefect_server
    - prefect_worker
    - dataset

- hosts: workers
  roles:
    - dask_worker
    - grobid_server