- hosts: all
  roles:
    - common
    - pipeline_code
    - node_exporter
  
- hosts: controller
  roles:
    - dask_scheduler
    - minio_server
    - prefect_server
    - prefect_worker
    - dataset
    - prometheus
    - streamlit

- hosts: workers
  roles:
    - dask_worker
    - grobid_server